buildscript {
    ext.kotlin_version = '2.1.21'
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        mavenCentral()
    }
    dependencies {
        classpath "org.checkerframework:checkerframework-gradle-plugin:0.6.37"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'java'
}

apply plugin: "org.checkerframework"
apply plugin: 'kotlin'

group = 'ru.dverkask'
version = '1.0'

repositories {
    mavenCentral()
    maven {
        url "https://plugins.gradle.org/m2/"
    }
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    implementation 'org.json:json:20090211'

    compileOnly "io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT"

    implementation 'com.google.code.gson:gson:2.8.6'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}

jar {
    archiveFileName = 'SkinAnatomyAPI.jar'
}
kotlin {
    jvmToolchain(17)
}